MasterArticleBloger/Areas/Adminstrator/Pages/ArticleCategoryManagement/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using P.Application.Contracts.ArticleCategory;

namespace MasterArticleBlogger.Areas.Adminstrator.Pages.ArticleCategoryManagement;

public class CreateModel : PageModel
{
    public CreateModel(IArticleCategoryApplication articleCategoryApplication)
    {
        _ArticleCategoryApplication = articleCategoryApplication;
    }


    public readonly IArticleCategoryApplication _ArticleCategoryApplication;

    [BindProperty] public AddCategoryArticle CategoryArticleCommand { get; set; }

    public void OnGet()
    {
    }

    public RedirectToPageResult OnPost()
    {
        _ArticleCategoryApplication.Add(CategoryArticleCommand);
        return RedirectToPage("./List");
    }
}

MasterArticleBloger/Areas/Adminstrator/Pages/ArticleCategoryManagement/Update.cshtml.cs
using Microsoft.AspNetCore.Http.Headers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using P.Application.Contracts.ArticleCategory;

namespace MasterArticleBlogger.Areas.Adminstrator.Pages.ArticleCategoryManagement;

public class UpdateModel : PageModel
{
    public UpdateModel(IArticleCategoryApplication articleCategoryApplication)
    {
        ArticleCategoryApplication = articleCategoryApplication;
    }

    private IArticleCategoryApplication ArticleCategoryApplication { get; set; }
    [BindProperty] public UpdateCategoryArticle? UpdateCategoryArticle { get; set; }

    public IActionResult OnGet(long id)
    {
        UpdateCategoryArticle = ArticleCategoryApplication.GetUpdateCategoryArticle(id);
        RequestHeaders? typedHeaders =
            HttpContext.Request.GetTypedHeaders();

        string? httpReferer =
            typedHeaders?.Referer?.AbsoluteUri;
        if (UpdateCategoryArticle == null)
        {
            if (httpReferer == null)
                return RedirectToPage("/Index");
            return RedirectToPage(httpReferer);
        }

        return Page();
    }


    public RedirectToPageResult OnPost()
    {
        ArticleCategoryApplication.Update(UpdateCategoryArticle);
        return RedirectToPage("./List");
    }
}

MasterArticleBloger/Areas/Adminstrator/Pages/ArticleManagement/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using P.Application.Contracts.Article;
using P.Application.Contracts.ArticleCategory;

namespace MasterArticleBlogger.Areas.Adminstrator.Pages.ArticleManagement;

public class CreateModel : PageModel
{
    public CreateModel(IArticleApplication articleApplication, IArticleCategoryApplication articleCategory)
    {
        ArticleApplication = articleApplication;
        ArticleCategory = articleCategory;
    }

    public void OnGet()
    {
        SelectCategoryListItems = ArticleCategory.List().Select
        (x => new SelectListItem
            (x.Title, x.Id.ToString())).ToList();
    }

    private IArticleApplication ArticleApplication { get; set; }
    private IArticleCategoryApplication ArticleCategory { get; set; }
    [BindProperty] public CreateArticle CreateArticle { get; set; }

    public List<SelectListItem> SelectCategoryListItems { get; set; }

    //public  Createdmodel  createdModels { get; set; }
    public IActionResult OnPost()
    {
        if (ModelState.IsValid)
        {
            ArticleApplication.Add(CreateArticle);
            return RedirectToPage("./Index");
        }

        SelectCategoryListItems = ArticleCategory.List().Select
        (x => new SelectListItem
            (x.Title, x.Id.ToString())).ToList();
        return Page();
    }
}

MasterArticleBloger/Areas/Adminstrator/Pages/ArticleManagement/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using P.Application.Contracts.Article;

namespace MasterArticleBlogger.Areas.Adminstrator.Pages.ArticleManagement;

public class IndexModel : PageModel
{
    public IndexModel(IArticleApplication articleApplication)
    {
        ArticleApplication = articleApplication;
    }

    [BindProperty] public long Id { get; set; }
    private IArticleApplication ArticleApplication { get; set; }

    //public IEnumerable<ArticleViewModel> ArtileList { get; set; }
    public List<ArticleViewModel> ArtileList { get; set; }

    public void OnGet()
    {
        //    ArtileList = ArticleApplication.List();
        ArtileList = ArticleApplication.GetListOfArticleViewModel();
    }

    public RedirectToPageResult OnPostReStatus()
    {
        ArticleApplication.ReStatus(Id);
        return RedirectToPage("./Index");
    }
}

MasterArticleBloger/Areas/Adminstrator/Pages/ArticleManagement/Update.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using P.Application.Contracts.Article;
using P.Application.Contracts.ArticleCategory;

namespace MasterArticleBlogger.Areas.Adminstrator.Pages.ArticleManagement;

public class UpdateModel : PageModel
{
    [BindProperty] public UpdateArticle UpdateArticle { get; set; }

    public void OnGet(long id)
    {
        UpdateArticle = ArticleApplication.GetUpdateArticleById(id);
        if (UpdateArticle == null) return;
        SelectCategoryListItems = ArticleCategory.List().Select
        (x => new SelectListItem
            (x.Title, x.Id.ToString())).ToList();
    }

    public UpdateModel(IArticleApplication articleApplication, IArticleCategoryApplication articleCategory)
    {
        ArticleApplication = articleApplication;
        ArticleCategory = articleCategory;
    }

    public IActionResult OnPost()
    {
        if (ModelState.IsValid)
        {
            ArticleApplication.Update(UpdateArticle);
            return RedirectToPage("./Index");
        }

        SelectCategoryListItems = ArticleCategory.List().Select
        (x => new SelectListItem
            (x.Title, x.Id.ToString())).ToList();
        return Page();
    }


    private IArticleApplication ArticleApplication { get; set; }
    private IArticleCategoryApplication ArticleCategory { get; set; }


    public List<SelectListItem> SelectCategoryListItems { get; set; }
}

MasterArticleBloger/Areas/Adminstrator/Pages/ArticleManagement/Create.cshtml
@page
@model MasterArticleBlogger.Areas.Adminstrator.Pages.ArticleManagement.CreateModel
@{
}
<div class="content">

    <div class="container">
        <div class="row align-items-stretch no-gutters contact-wrap">
            <div class="col-md-12">
                <div class="form h-100">
                    <h3>Create Article</h3>
                    <form class="mb-5" method="post">
                        <div class="row">
                            <div class="col-md-12 form-group mb-3">
                                <label asp-for="CreateArticle.Title" class="col-form-label">Title* </label>
                                <input asp-for="CreateArticle.Title" class="form-control" placeholder="Write Title" ></input>
                                <span class="text-danger" asp-validation-for="CreateArticle.Title"></span>
                            </div>

                            <div class="col-md-12 form-group mb-3">
                                <label asp-for="CreateArticle.Image" class="col-form-label">Image Path* </label>
                                <input asp-for="CreateArticle.Image" class="form-control"  placeholder="Enter Your Image Path" ></input>
                                <span class="text-danger" asp-validation-for="CreateArticle.Image"></span>
                            </div>

                            <div class="col-md-12 form-group mb-3">
                                <label asp-for="CreateArticle.ShortDescription"  class="col-form-label">ShortDescription *</label>
                                <input asp-for="CreateArticle.ShortDescription"  class="form-control"  placeho holder="ShortDescription" >
                                <span class="text-danger" asp-validation-for="CreateArticle.ShortDescription"></span>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12 form-group mb-3">
                                <label asp-for="CreateArticle.ArticleCategoryId" class="col-form-label form-check">Select Article Category *</label>
                                <select asp-for="CreateArticle.ArticleCategoryId" class="custom-select" asp-items="Model.SelectCategoryListItems">
                                    <option selected>Choose...</option>
                                </select>
                                <span class="text-danger" asp-validation-for="CreateArticle.ArticleCategoryId"></span>
                                </div>
                            
                        </div>
                        <div class="row">
                            <div class="col-md-12 form-group mb-3">
                                <label asp-for="CreateArticle.Content" class="col-form-label">Content </label>
                                <textarea asp-for="CreateArticle.Content" class="form-control" cols="30" rows="4" placeholder="Write your Content"></textarea>
                                <span class="text-danger" asp-validation-for="CreateArticle.Content"></span>
                                </div>
                              
                        </div>
                        <div class="row">
                            <div class="col-md-12 form-group">
                                <input type="submit" value="Send Message" class="btn btn-primary rounded py-2 px-4">
                                <span class="text-danger" class="submitting"></span>
                            </div>
                        </div>
                    </form>
                    
               
                </div>
            </div>
        </div>
    </div>

</div>

MasterArticleBloger/Areas/Adminstrator/Pages/ArticleManagement/Index.cshtml
@page
@model MasterArticleBlogger.Areas.Adminstrator.Pages.ArticleManagement.IndexModel
@{
}
<div  class="card">
    <div class="card-header">
        <h3 class="float-left">Article List</h3>
        <div class="float-right">
            <a class="btn btn-success"  asp-area="Adminstrator" asp-page="/ArticleManagement/Create">Add New</a>
        </div>
    </div>
    <div class="card-body">
        <table class="table table-dark ">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Id</th>
                <th scope="col">Name</th>
                <th scope="col">Status</th>
                <th scope="col">Creation Date</th>
                <th scope="col">Update</th>
                <th scope="col">Change Status</th>
            </tr>
            </thead>
            <tbody class="table-light text-dark table-hover">
            @{
                int i = 1; 
            }
            @foreach (var article in Model.ArtileList)
            {
                <tr class="table-hover">
                    <th scope="row">@(i)</th>
                    <td>@article.Id</td>
                    <td>@article.Title</td>
                    <td>@article.ArticleCategory</td>
                    <td>@if (@article.IsDeleted)
                        {
                            <i class="fa fa-close fa-2x text-danger"></i>
                        }
                        else
                        {
                            <i class="fa fa-check fa-2x text-success"></i>
                        }
                    </td>
                    <td>@article.CreationDate</td>
                    <td><a asp-area="Adminstrator" asp-page="/ArticleManagement/Update" asp-route-id="@article.Id" class="btn btn-warning">Update</a></td>
                    <td>
                        <form method="post" asp-page-handler="ReStatus" >
                            @if (article.IsDeleted)
                                {
                                <button type="submit" class="btn btn-success">Active</button>
                                }
                            else
                            {
                                <button type="submit" class="btn btn-danger">Delete</button>
                            }
                            <input type="hidden" asp-for="@Model.Id" value="@article.Id"/>
                        </form>
                    </td>
                </tr>
                i++;
            }
            </tbody>
        </table>
    </div>
</div>

MasterArticleBloger/Areas/Adminstrator/Pages/ArticleManagement/Update.cshtml
@page
@model MasterArticleBlogger.Areas.Adminstrator.Pages.ArticleManagement.UpdateModel
@{
}
<div class="content">
    <div class="container">
        <div class="row align-items-stretch no-gutters contact-wrap">
            <div class="col-md-12">
                <div class="form h-100">
                    <h3>Create Article</h3>
                    <form class="mb-5" method="post">
                        <div class="row">
                            <div class="col-md-12 form-group mb-3">
                                <label asp-for="UpdateArticle.Title" class="col-form-label">Title* </label>
                                <input asp-for="UpdateArticle.Title" class="form-control" placeholder="Write Title"></input>
                                 <span class="text-danger"  asp-validation-for="UpdateArticle.Title"></span>
                            </div>
                            <div class="col-md-12 form-group mb-3">
                                <label asp-for="UpdateArticle.Image" class="col-form-label">Image Path* </label>
                                <input asp-for="UpdateArticle.Image" class="form-control" placeholder="Enter Yoyr Image Path"></input>
                                 <span class="text-danger" asp-validation-for="UpdateArticle.Image"></span>
                            </div>

                            <div class="col-md-12 form-group mb-3">
                                <label asp-for="UpdateArticle.ShortDescription" class="col-form-label">ShortDescription *</label>
                                <input asp-for="UpdateArticle.ShortDescription" class="form-control" placeho holder="ShortDescription">
                                 <span class="text-danger" asp-validation-for="UpdateArticle.ShortDescription"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12 form-group mb-3">
                                <label asp-for="UpdateArticle.ArticleCategoryId" class="col-form-label form-check">Select Article Category *</label>
                                <select asp-for="UpdateArticle.ArticleCategoryId" class="custom-select" asp-items="Model.SelectCategoryListItems">
                                    <option selected>Choose...</option>
                                </select>
                                 <span class="text-danger" asp-validation-for="UpdateArticle.ArticleCategoryId"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12 form-group mb-3">
                                <label asp-for="UpdateArticle.Content" class="col-form-label">Content </label>
                                <textarea asp-for="UpdateArticle.Content" class="form-control" cols="30" rows="4" placeholder="Write your Content"></textarea>
                                 <span class="text-danger" asp-validation-for="UpdateArticle.Content"></span>
                            </div>
                        </div>
                        <input type="hidden" asp-for="UpdateArticle.Id" />
                         <span class="text-danger" asp-validation-for="UpdateArticle.Id"></span>
                        <div class="row">
                            <div class="col-md-12 form-group">
                                <input type="submit" value="Send Message" class="btn btn-primary rounded py-2 px-4">
                                
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>