MasterArticleBloger/Areas/Adminstrator/Pages/CommentManagement/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using P.Application.Contracts.Comment;

namespace MasterArticleBlogger.Areas.Adminstrator.Pages.CommentManagement;

public class IndexModel : PageModel
{
    public IndexModel(ICommentApplication commentApplication)
    {
        CommentApplication = commentApplication;
    }

    public List<CommentViewModel> Comments { get; set; }
    private ICommentApplication CommentApplication { get; }

    public void OnGet()
    {
        Comments = CommentApplication.GetAllViewModels();
    }

    public RedirectToPageResult OnPostConfirmComment(long id)
    {
        CommentApplication.ConfirmOrActive(id);
        return RedirectToPage();
    }

    public RedirectToPageResult OnPostRemoveComment(long id)
    {
        CommentApplication.RemoveComment(id);
        return RedirectToPage();
    }
}

MasterArticleBloger/Areas/Adminstrator/Pages/CommentManagement/Index.cshtml
@page
@model MasterArticleBlogger.Areas.Adminstrator.Pages.CommentManagement.IndexModel
@{
}
<div class="card">
    <div class="card-header">
        <h3 class="float-left">Article Category List</h3>
        <div class="float-right">
            <a class="btn btn-success" asp-area="Adminstrator" asp-page="/ArticleCategoryManagement/Create">Add New</a>
        </div>
    </div>
    <div class="card-body">
        <table class="table table-dark ">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Id</th>
                    <th scope="col">Username</th>
                    <th scope="col">Article Name</th>
                    <th scope="col">Status</th>
                    <th scope="col">Creation Date</th>
                    <th scope="col">Change Status</th>
                </tr>
            </thead>
            <tbody class="table-light text-dark table-hover">
                @{
                    int i = 1;
                }
                @foreach (var comment in Model.Comments)
                {
                    <tr class="table-hover">
                        <th scope="row">@(i)</th>
                        <td>@comment.Id</td>
                        <td>@comment.Name</td>
                        <td>@comment.Article</td>
                        <td>
                            @if (@comment.Status == 0)
                            {
                                <i class="fa fa-eye fa-2x text-info"></i>
                            }
                            else
                            {
                                if (@comment.Status == 1)
                                {
                                    <i class="fa fa-check fa-2x text-success"></i>
                                }
                                else
                                {
                                    <i class="fa fa-close fa-2x text-danger"></i>
                                }
                            }
                        </td>
                        <td>@comment.CreationDate</td>
                        <td>
                            @{
                                if (comment.Status == 0)
                                {
                                    <form method="post" asp-page-handler="ConfirmComment">
                                        <input name="id" value="@comment.Id" type="hidden" />
                                        <button type="submit" class="btn btn-success"> Confirm </button>
                                    </form>
                                }
                                else if (comment.Status == 2)
                                {
                                    <form method="post" asp-page-handler="ConfirmComment">
                                        <input name="id" value="@comment.Id" type="hidden" />
                                        <button type="submit" class="btn btn-success"> Active </button>
                                    </form>
                                }
                                else
                                {
                                    <form method="post" asp-page-handler="RemoveComment">
                                        <input name="id" value="@comment.Id" type="hidden" />
                                        <button type="submit" class="btn btn-danger">Delete</button>
                                    </form>
                                }
                            }
                        </td>
                    </tr>
                    i++;
                }
            </tbody>
        </table>
    </div>
</div>